service: aws-go-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  profile: serverlessUser
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:Scan"
          Resource: 
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/Trips"
        - Effect: Allow
          Action: 
            - "bedrock:InvokeModel"
          Resource: "*"

plugins:
  - serverless-go-plugin

functions:
  register:
    handler: './RegisterTrip'
    events:
      - httpApi:
          path: /trips
          method: post
  list:
    handler: './ListTrips'
    events:
      - httpApi:
          path: /trips
          method: get
  guide:
    handler: './TripIA'
    timeout: 20
    events:
      - httpApi:
          path: /guide
          method: post

custom:
  go:
    supportedRuntimes: ["provided.al2"]
    buildProvidedRuntimeAsBootstrap: true

resources:
  Resources:
    TripTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Trips
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1